version: '3.9'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: kara_solutions
      POSTGRES_USER: mebsahle
      POSTGRES_PASSWORD: psql
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mebsahle -d kara_solutions"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
      - ./.dbt:/root/.dbt
    depends_on:
      db:
        condition: service_healthy
    command: tail -f /dev/null

  api:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  pg_data: